// Generated by LiveScript 1.4.0
(function(){
  var fs, gm, async;
  fs = require('fs');
  gm = require('gm');
  async = require('async');
  exports.resizeAndCrop = function(form, file, done){
    fs.rename(file.path, form.uploadDir + '/' + file.name);
    return async.parallel([
      function(callback){
        var size;
        size = {
          width: 1200,
          height: 800
        };
        return gm(form.uploadDir + '/' + file.name).resize(size.width, size.height + '^').gravity('Center').extent(size.width, size.height).quality(80).antialias(false).noProfile().interlace('PlaneInterlace').write(form.uploadDir + '/large/' + file.name, function(err){
          if (err) {
            return err;
          }
          console.log('Resized to 1200x800');
          return callback(null, 'large');
        });
      }, function(callback){
        var size;
        size = {
          width: 400,
          height: 300
        };
        return gm(form.uploadDir + '/' + file.name).resize(size.width, size.height + '^').gravity('Center').antialias(false).extent(size.width, size.height).quality(80).noProfile().interlace('PlaneInterlace').write(form.uploadDir + '/small/' + file.name, function(err){
          if (err) {
            return err;
          }
          console.log('Resized to 450x450');
          return callback(null, 'small');
        });
      }, function(callback){
        var size;
        size = {
          width: 120,
          height: 120
        };
        return gm(form.uploadDir + '/' + file.name).resize(size.width, size.height + '^').gravity('Center').antialias(false).extent(size.width, size.height).quality(100).noProfile().interlace('PlaneInterlace').write(form.uploadDir + '/tiny/' + file.name, function(err){
          if (err) {
            return err;
          }
          console.log('Resized to 120x120 & Cropped');
          return callback(null, 'thumbnail');
        });
      }, function(callback){
        var size;
        size = {
          width: 1200,
          height: 800
        };
        return gm(form.uploadDir + '/' + file.name).resize(size.width, size.height + '^').gravity('Center').extent(size.width, size.height).quality(100).blur(30, 20).antialias(true).noProfile().interlace('PlaneInterlace').write(form.uploadDir + '/large/blur/' + file.name, function(err){
          if (err) {
            return err;
          }
          console.log('Resized to 1200x800 and blured');
          return callback(null, 'blurry');
        });
      }
    ], function(err, results){
      return done();
    });
  };
}).call(this);
