// Generated by LiveScript 1.4.0
(function(){
  var latiniseJs;
  latiniseJs = require('../config/latinise');
  exports.setSlug = function(slug){
    var Latinise;
    Latinise = {};
    Latinise.latin_map = latiniseJs;
    String.prototype.latinise = function(){
      return this.replace(/[^A-Za-z0-9\[\] ]/g, function(a){
        return Latinise.latin_map[a] || a;
      });
    };
    String.prototype.latinize = String.prototype.latinise;
    String.prototype.isLatin = function(){
      return this === this.latinise();
    };
    return slug.split(' ').join('-').split('\'').join('-').toLowerCase().latinize();
  };
}).call(this);
