// Generated by LiveScript 1.4.0
(function(){
  var app, passport, env, port, climate, config, mongoose, options;
  app = require('express')();
  passport = require('passport');
  env = function(){
    var Habitat;
    Habitat = require('habitat');
    Habitat.load('.env');
    return new Habitat;
  }();
  port = env.get('TRACKLIST_PORT');
  climate = env.get('TRACKLIST_ENV');
  config = require('./app/config/config')[climate];
  mongoose = require('mongoose');
  options = {
    db: {
      native_parser: true
    },
    server: {
      poolSize: 5
    }
  };
  mongoose.connect(config.db, options);
  require('./app/config/passport')(passport, config);
  require('./app/config/express')(app, config, env, passport);
  require('./app/config/routes')(app, passport);
  app.listen(port, '127.0.0.1', function(){
    return console.log('Tracklist API is running in ', app.get('env'), ' mode on port ', port);
  });
}).call(this);
