// Generated by LiveScript 1.4.0
(function(){
  var gulp, gulpLiveScript;
  gulp = require('gulp');
  gulpLiveScript = require('gulp-livescript');
  gulp.task('ls', function(){
    return gulp.src('./*.ls').pipe(gulpLiveScript({
      bare: true
    })).pipe(gulp.dest('.'));
  });
  gulp.task('watch', function(){
    return gulp.watch('./', ['ls']);
  });
  gulp.task('default', ['ls', 'watch']);
}).call(this);
