// Generated by LiveScript 1.4.0
(function(){
  var Label;
  Label = require('../models/label');
  module.exports = {
    create: function(req, res, next){
      var label;
      return label = new Label({
        name: req.body.name
      }).save(function(err, label){
        if (err) {
          return next(err);
        }
        return res.json(label);
      });
    },
    list: function(req, res, next){
      return Label.find().exec(function(err, labels){
        if (err) {
          return next(err);
        }
        return res.json({
          labels: labels
        });
      });
    },
    show: function(req, res, next){
      return Label.findOne({
        permalink: req.params.permalink
      }).populate({
        path: 'artists._artist'
      }).exec(function(err, label){
        if (err) {
          return next(err);
        }
        return res.json(label);
      });
    },
    update: function(req, res){
      return Label.findOneAndUpdate({
        permalink: req.params.permalink
      }, req.body, {
        upsert: true
      }, function(err, label){
        if (err) {
          return next(err);
        }
        return res.sendStatus(200).json(label);
      });
    },
    remove: function(req, res){}
  };
}).call(this);
