// Generated by LiveScript 1.4.0
(function(){
  var mongoose, Event, async, _;
  mongoose = require('mongoose');
  Event = require('../../models/event');
  async = require('async');
  _ = require('lodash');
  exports.requiresLogin = function(req, res, next){
    if (!req.headers['x-tracklist-session-id']) {
      return res.status(500).send({
        error: 'You are not authorized to access this ressource'
      });
    }
    return mongoose.connection.db.collection('sessions', function(err, collection){
      return collection.findOne({
        '_id': req.headers['x-tracklist-session-id']
      }, function(err, res){
        var session;
        session = JSON.parse(res.session);
        if (Boolean(session !== undefined)) {
          req.user = session.passport.user;
          return next();
        } else {
          return res.status(500).send({
            error: 'You are not authorized to access this ressource'
          });
        }
      });
    });
  };
  exports.eventAuth = function(req, res, next){
    var eventId;
    eventId = req.params.id;
    return mongoose.connection.db.collection('sessions', function(err, collection){
      return collection.findOne({
        '_id': req.headers['x-tracklist-session-id']
      }, function(err, res){
        var session;
        session = JSON.parse(res.session);
        if (Boolean(session !== undefined)) {
          return next();
        } else {
          return res.status(500).send(401, {
            error: 'You are not authorized to access this ressource'
          });
        }
      });
    });
  };
}).call(this);
