// Generated by LiveScript 1.4.0
(function(){
  var mongoose, async, _;
  mongoose = require('mongoose');
  async = require('async');
  _ = require('lodash');
  exports.requiresInt = function(req, res, next){
    if (_.isNan(req.params.id)) {
      return res.status(400).send({
        error: 'Param id must be an integer'
      });
    }
    return next();
  };
}).call(this);
