// Generated by LiveScript 1.4.0
(function(){
  var mongoose, autoIncrement, validate, slug, Schema, uriValidator, TrackSchema;
  mongoose = require('mongoose');
  autoIncrement = require('mongoose-auto-increment');
  validate = require('mongoose-validator');
  slug = require('../lib/slug');
  Schema = mongoose.Schema;
  autoIncrement.initialize(mongoose);
  uriValidator = [validate({
    validator: 'isLength',
    arguments: [20, 100],
    message: 'Title should be between 3 and 50 characters'
  })];
  TrackSchema = new Schema({
    id: Number,
    events: [{
      _event: {
        type: Number,
        ref: 'Event'
      }
    }],
    source: String,
    uri: String,
    url: String,
    createdAt: {
      type: Date,
      'default': Date.now
    }
  }, {
    strict: true
  });
  TrackSchema.plugin(autoIncrement.plugin, {
    model: 'Track',
    field: 'id',
    startAt: 1,
    incrementBy: 1
  });
  module.exports = mongoose.model('Track', TrackSchema);
}).call(this);
